version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres_anime
    restart: always
    environment:
      POSTGRES_USER: ayush
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: anime_db
    ports:
      - "5432:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
